# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
osx_image: xcode9.3
# cache: cocoapods
# podfile: Example/Podfile
before_install:
- gem install cocoapods --no-rdoc --no-ri --no-document --quiet
- pod repo update
script:
- set -o pipefail
- xcodebuild test -workspace Example/WistiaKit.xcworkspace -scheme WistiaKit-Example -destination 'platform=iOS Simulator,name=iPhone 8,OS=11.3' ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
